def _select_current_close_event(issue_data):
    # ...
    if close_event is None:
        return None  # treated as “lookup failed”
    # ...
def find_solver_from_closure_event(issue_data):
    # ...
    close_event = _select_current_close_event(issue_data)
    if close_event is None:
        return (None, None)  # treated as “lookup failed”
    # ...
    solver_lookup_failed = False
    solver_github_id, pr_number = solver_lookup
    # ...