# Vulture whitelist: each bare name below counts as a use, suppressing the
# matching report. Prefer this over `[tool.vulture] ignore_names` (global)
#
# Auto-generated entries below come from `uv run vulture --make-whitelist`
# Hand-curated entries (with explanatory comments) precede them

# ruff: noqa: F821

# `__exit__(self, exc_type, exc, tb)` - PEP 343 signature, body unused args
exc_type
tb

# `ttl_cache` lru_cache cache-buster arg (gittensor/utils/misc.py)
ttl_hash

# Cache-fallback diagnostics.
mirror_pr_fetch_failed
_.mirror_pr_fetch_failed
_.should_use_cache_fallback

# Compute gateway: FastAPI route handlers registered by decorator; Usage fields reach the usage line via asdict()
healthz
completions
http_passthrough
total_ms
_.total_ms

# Compute controller: in-lease watch fields reach instances.json via asdict() (WS-F and `status` read them there);
# BoxLocks.held is the round's view of a busy box, exercised in tests
heartbeat_ok
_.heartbeat_ok
heartbeat_misses
_.heartbeat_misses
_.heartbeat
_.held
# BoxState.admitted_at is also cleared when discovery benches a deregistered box (read through asdict)
_.admitted_at

# Compute config surface: image paths the agent/runner Dockerfiles mirror (CA_PUBKEY_PATH is asserted in tests), and
# the proof fill ratios the gt-proof provider package reads by name
CA_PUBKEY_PATH
ALLOWED_SIGNERS_PATH
PROOF_FILL_RATIO
PROOF_FILL_FLOOR_RATIO

# Compute checks package: PEP 562 lazy attribute; run_full_check / due_for_check are its exported entry points, driven
# by tests; load_manifest is what the bless-image workflow calls; regex is the FakeRunner matcher the tests use
__getattr__
run_full_check
due_for_check
load_manifest
regex

# GPU proof protocol: StagedProof.challenges is filled and read by the provider (gt-proof); vram_total_bytes is a
# GpuProof.judge parameter UnconfiguredProof ignores
challenges
vram_total_bytes

# Scraped / minted data read only in tests: GpuInfo's extra nvidia-smi columns, VisitCredential.not_before,
# SshRunner.minted, StateStore.by_status, GpuRate.leased_to_idle; artifact_sha256 is exec'd from the template's
# entrypoint scheme and checked against it in tests
power_max_limit_w
pci_bus_id
not_before
_.minted
_.by_status
_.leased_to_idle
artifact_sha256

# --- Auto-generated by `uv run vulture --make-whitelist` ---
MERGED  # unused variable (gittensor/classes.py:35)
OPEN  # unused variable (gittensor/classes.py:36)
CLOSED  # unused variable (gittensor/classes.py:37)
body_or_title_edited_at  # unused variable (gittensor/classes.py:133)
head_ref_oid  # unused variable (gittensor/classes.py:198)
base_ref_oid  # unused variable (gittensor/classes.py:199)
command_class  # unused variable (gittensor/cli/issue_commands/help.py:147)
_.autocommit  # unused attribute (gittensor/validator/storage/database.py:40)
_.prepare_threshold  # unused attribute (gittensor/validator/storage/database.py:42)
WANDB_API_KEY  # unused variable (gittensor/validator/utils/config.py:10)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:51)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:88)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:93)
_.timeout_micros  # unused attribute (gittensor/validator/utils/tree_sitter_scoring.py:56)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:18)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:48)
parse_optional_github_iso_to_utc  # unused function (gittensor/validator/utils/datetime_utils.py:24)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:125)
_.ttl_get_block  # unused method (gittensor/utils/misc.py:91)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:180)
add_validator_args  # unused function (gittensor/utils/config.py:81)
