# Vulture whitelist: each bare name below counts as a use, suppressing the
# matching report. Prefer this over `[tool.vulture] ignore_names` (global)
#
# Auto-generated entries below come from `uv run vulture --make-whitelist`
# Hand-curated entries (with explanatory comments) precede them

# ruff: noqa: F821

# Serving beta: FastAPI route handlers are registered via decorator, not called directly;
# telemetry fields/helpers are read by operators via /v1/serving/status and tests.
health
models
chat_completions
_close_dendrite
serving_api
completion_tokens
inflight
as_dict
reference_completion
should_exit
ts
ECHO_LOADOUT_PATH

# `__exit__(self, exc_type, exc, tb)` - PEP 343 signature, body unused args
exc_type
tb

# `ttl_cache` lru_cache cache-buster arg (gittensor/utils/misc.py)
ttl_hash

# Cache-fallback diagnostics.
mirror_pr_fetch_failed
_.mirror_pr_fetch_failed
_.should_use_cache_fallback

# --- Auto-generated by `uv run vulture --make-whitelist` ---
MERGED  # unused variable (gittensor/classes.py:35)
OPEN  # unused variable (gittensor/classes.py:36)
CLOSED  # unused variable (gittensor/classes.py:37)
body_or_title_edited_at  # unused variable (gittensor/classes.py:133)
head_ref_oid  # unused variable (gittensor/classes.py:198)
base_ref_oid  # unused variable (gittensor/classes.py:199)
command_class  # unused variable (gittensor/cli/issue_commands/help.py:147)
_.autocommit  # unused attribute (gittensor/validator/storage/database.py:40)
_.prepare_threshold  # unused attribute (gittensor/validator/storage/database.py:42)
WANDB_API_KEY  # unused variable (gittensor/validator/utils/config.py:10)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:51)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:88)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:93)
_.timeout_micros  # unused attribute (gittensor/validator/utils/tree_sitter_scoring.py:56)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:18)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:48)
parse_optional_github_iso_to_utc  # unused function (gittensor/validator/utils/datetime_utils.py:24)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:125)
_.ttl_get_block  # unused method (gittensor/utils/misc.py:91)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:180)
add_validator_args  # unused function (gittensor/utils/config.py:81)
neuron_type  # class attr read by BaseNeuron.should_set_weights (neurons/serving_miner.py:47)
