# Vulture whitelist: each bare name below counts as a use, suppressing the
# matching report. Prefer this over `[tool.vulture] ignore_names` (global)
#
# Auto-generated entries below come from `uv run vulture --make-whitelist`
# Hand-curated entries (with explanatory comments) precede them

# ruff: noqa: F821

# `__exit__(self, exc_type, exc, tb)` - PEP 343 signature, body unused args
exc_type
tb

# `ttl_cache` lru_cache cache-buster arg (gittensor/utils/misc.py)
ttl_hash

# --- Auto-generated by `uv run vulture --make-whitelist` ---
MERGED  # unused variable (gittensor/classes.py:35)
OPEN  # unused variable (gittensor/classes.py:36)
CLOSED  # unused variable (gittensor/classes.py:37)
body_or_title_edited_at  # unused variable (gittensor/classes.py:133)
head_ref_oid  # unused variable (gittensor/classes.py:198)
base_ref_oid  # unused variable (gittensor/classes.py:199)
command_class  # unused variable (gittensor/cli/issue_commands/help.py:147)
author_id  # unused variable (gittensor/utils/models.py:16)
review_count  # unused variable (gittensor/utils/models.py:21)
_.autocommit  # unused attribute (gittensor/validator/storage/database.py:40)
_.prepare_threshold  # unused attribute (gittensor/validator/storage/database.py:42)
WANDB_API_KEY  # unused variable (gittensor/validator/utils/config.py:10)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:51)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:88)
_.autocommit  # unused attribute (gittensor/validator/utils/storage.py:93)
_.timeout_micros  # unused attribute (gittensor/validator/utils/tree_sitter_scoring.py:56)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:18)
_.convert  # unused method (gittensor/cli/issue_commands/types.py:48)
parse_optional_github_iso_to_utc  # unused function (gittensor/validator/utils/datetime_utils.py:24)
read_contract_packed_storage  # unused function (gittensor/validator/issue_competitions/storage_utils.py:125)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:125)
_.ttl_get_block  # unused method (gittensor/utils/misc.py:91)
_.get_help  # unused method (gittensor/cli/issue_commands/help.py:180)
add_validator_args  # unused function (gittensor/utils/config.py:81)
