# Entrius 2025
"""Backward-compatible entrypoint for GitHub API utilities."""

from gittensor.utils.github_api import (
    QUERY,
    FileContentPair,
    GraphQLPageResult,
    _search_issue_referencing_prs_graphql,
    _search_issue_referencing_prs_rest,
    branch_matches_pattern,
    check_github_issue_closed,
    execute_graphql_query,
    fetch_file_contents_batch,
    fetch_file_contents_with_base,
    find_prs_for_issue,
    find_solver_from_cross_references,
    find_solver_from_timeline,
    get_github_graphql_query,
    get_github_id,
    get_github_user,
    get_merge_base_sha,
    get_pull_request_file_changes,
    get_pull_request_maintainer_changes_requested_count,
    load_miners_prs,
    make_headers,
    should_skip_merged_pr,
    try_add_open_or_closed_pr,
)

__all__ = [
    'QUERY',
    'GraphQLPageResult',
    'FileContentPair',
    '_search_issue_referencing_prs_graphql',
    '_search_issue_referencing_prs_rest',
    'branch_matches_pattern',
    'check_github_issue_closed',
    'execute_graphql_query',
    'fetch_file_contents_batch',
    'fetch_file_contents_with_base',
    'find_prs_for_issue',
    'find_solver_from_cross_references',
    'find_solver_from_timeline',
    'get_github_graphql_query',
    'get_github_id',
    'get_github_user',
    'get_merge_base_sha',
    'get_pull_request_file_changes',
    'get_pull_request_maintainer_changes_requested_count',
    'load_miners_prs',
    'make_headers',
    'should_skip_merged_pr',
    'try_add_open_or_closed_pr',
]
